runtime: go120
service: weve-esi-go
app_engine_apis: true
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
  max_concurrent_requests: 500
  # max_pending_latency: 10s
  # min_pending_latency: 1s
  max_idle_instances: 1
# instance_class: B1
# basic_scaling:
#   max_instances: 1
#   idle_timeout: 5m

env_variables:
  SERVE_ADDRESS: 0.0.0.0:8080
  # Go Duration
  CLIENT_TIMEOUT: '##CLIENT_TIMEOUT##'
  # String
  CLIENT_ID: '##CLIENT_ID##'
  CLIENT_SECRET: '##CLIENT_SECRET##'
  USER_AGENT: '##USER_AGENT##'
