runtime: go120
service: weve-esi-go
instance_class: F1
env_variables:
  LISTEN_ADDRESS: 127.0.0.1:8080
  # Go Duration
  CLIENT_TIMEOUT: ##CLIENT_TIMEOUT##
  # String
  CLIENT_ID: ##CLIENT_ID##
  CLIENT_SECRET: ##CLIENT_SECRET##
  USER_AGENT: ##USER_AGENT##
